apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- ns.yaml
configMapGenerator:
- name: cert-manager-patch-${cluster_name}
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true