apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:nzXvwLUzhBI=,iv:HICMOdDKOqqJP46Xb5dVlaJfehh7ZXAS0l/SVWeupDk=,tag:SdVzG3h/nsZckzoBUPg6yg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-issuer-example-com-secret
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgyfulm6pdm460m436umjgfmultg7fl3fl0r46hs45yngw5uxffsc5w4y7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaGY4WTV1bysza0N4RUZY
            amYvTTVZTXZ3QzhiTFJ0YmgwTG1EeHV0T25jCkpGV0J1ZzFQMXNaWDRTekxXd2Fu
            UFFzNktCaEgzNVF2SEFQS29pQlVZQW8KLS0tIHcwSEozdmxXK2dKVDBKU24yUlZl
            TU1CWDZXc1BES2Vaa0hSYW5hcmEwUTAKQl8mVBepmKnaTatH64LUMigFE97B2fly
            6FMgOgUU+Un2KxxBp2uxTgKlO2DL5c3vAwheLexX/4bD3jt3kX5Yvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T10:08:11Z"
    mac: ENC[AES256_GCM,data:vF45Yy3uXtOX1k+Z+EwVSy6F2UdCOXvV4njHZ0E4DjB9YfjOxVJ2j7uSPIRkj9+a8ZDUVXh+dN1MLsbt3fxwXLOQhPWQj5CgTUoIwAflpPuisJxsC86Odkl+X74nyLw7N8n/sbHJt6ZqNqlUyrvD7tdwM+dVSEe0V0+qZAhTsyY=,iv:cJtACMIwKXLCrTAtijK9ghzy2w3CSxKM+6WHT0QauIo=,tag:D6YAwC9JaCGi2IpmdOB7jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
