---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: postmaster@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
        - "example.com"
      dns01:
        cloudflare:
          email: postmaster@example.com
          apiTokenSecretRef:
            name: cluster-issuer-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: postmaster@example.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
        - "example.com"
        cloudflare:
          email: postmaster@example.com
          apiTokenSecretRef:
            name: cluster-issuer-secret
            key: api-token