apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications
spec:
  path: ./applications/clusters/prod/
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system