apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
spec:
  releaseName: argocd
  interval: 5m0s
  maxHistory: 3
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: argo-cd
      version: 4.10.6
      sourceRef:
        kind: HelmRepository
        name: argo-charts
        namespace: argo-system
      interval: 5m0s
  values:
    global:
      networkPolicy:
        create: true
        defaultDenyIngress: true

    controller:
      enableStatefulSet: true
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

    dex:
      enabled: false

    redis:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

    repoServer:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

    server:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true

      ingress:
        enabled: false
        annotations:
          ingress.kubernetes.io/force-ssl-redirect: "true"
        ingressClassName: nginx