apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
spec:
  path:  "./infrastructure/clusters/${cluster_name}/cert-manager"
  targetNamespace: cert-manager
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system