apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
spec:
  path:  "./infrastructure/clusters/${cluster_name}/cert-manager"
  targetNamespace: cert-manager
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-system
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: HelmRepository
      name: jetstack-charts
      namespace: cert-system
