apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- release.yaml
- repository.yaml
- ns.yaml
patchesStrategicMerge:
- ../../clusters/${cluster_name}/infrastructure/cert-manager/patch.yaml