apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  maxHistory: 3
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.9.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: cert-manager
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
    - kind: ConfigMap
      name: cert-manager-patch-${cluster_name}