---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  postBuild:
    substitute:
      cluster_name: "prod"
  #decryption:
  #  provider: sops
  #  secretRef:
  #    name: sops-gpg-flux-global-prod