apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuers
spec:
  path: ./infrastructure/clusters/prod/cert-manager/issuers
  targetNamespace: cert-manager
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  #decryption:
  #  provider: sops
  #  secretRef:
  #    name: sops-gpg-flux-global-prod