apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  maxHistory: 3
  interval: 5m0s
  install:
    skipCRDs: true
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: ingress
      interval: 5m0s
  values:
    controller:
      config:
        # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotation-value-word-blocklist
        annotation-value-word-blocklist: "load_module,lua_package,_by_lua,location,root,proxy_pass,serviceaccount,{,},',\\"
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 200Mi
      metrics:
        enabled: true