apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  path: ./infrastructure/clusters/prod/ingress-nginx
  targetNamespace: ingress
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system