apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: ./infrastructure/cert-manager
  targetNamespace: cert-manager
  prune: true
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
